map_name_mapping = {
    "arx": "Arx Novena",
    "arxnovena": "Arx Novena",
    "bella": "Bella Omega",
    "bella omega ns": "Bella Omega",
    "ccr": "Canyon Crusade Revival",
    "community": "Community",
    "dodgemap": "Community",
    "dangerouscrossing": "Dangerous Crossing",
    "dx": "Dangerous Crossing",
    "dd": "Drydock",
    "drydock": "Drydock",
    "fracture": "Fracture",
    "kata": "Katabatic",
    "katabatic": "Katabatic",
    "oceanus": "Oceanus",
    "other": "Other",
    "perma": "Perma",
    "permafrost": "Perma",
    "raindance": "Raindance",
    "rd": "Raindance",
    "ss": "Sunstar",
    "sunstar": "Sunstar",
    "styx": "Styx",
    "blues": "Blues",
    "tartar": "Tartarus",
    "tartarus": "Tartarus",
    "walledin": "Walled In",
    "lavaarena": "Lava Arena",
    "elysianbattlegrounds": "Elysian Battlegrounds"
}
